CONFIG_RGBLED_WIDGET=y
CONFIG_RGBLED_WIDGET_SHOW_LAYER_COLORS=y

# Layer colors: 0=Black, 1=Red, 2=Green, 3=Yellow, 4=Blue, 5=Magenta, 6=Cyan, 7=White
# 0 mac_default / 1 win_default: off
CONFIG_RGBLED_WIDGET_LAYER_0_COLOR=0
CONFIG_RGBLED_WIDGET_LAYER_1_COLOR=0
CONFIG_RGBLED_WIDGET_LAYER_2_COLOR=2
CONFIG_RGBLED_WIDGET_LAYER_3_COLOR=4
CONFIG_RGBLED_WIDGET_LAYER_4_COLOR=3
CONFIG_RGBLED_WIDGET_LAYER_5_COLOR=7
CONFIG_RGBLED_WIDGET_LAYER_6_COLOR=7
